version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw

  - package-ecosystem: npm
    directory: "/packages/async-wrapper"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw

  - package-ecosystem: npm
    directory: "/packages/base64"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw

  - package-ecosystem: npm
    directory: "/packages/logger"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw
