name: Documentation

on:
  push:
    branches: [main]
    paths:
      - packages/**/src/**
      - typedoc.json
      - README.md
      - .github/workflows/documentation.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: main
        run: |
          yarn ci
          yarn lint
          yarn bootstrap
          yarn test:ci
          yarn docs

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs

      - run: cp ./main/docs/* docs -r
      - run: cp ./main/README.md docs -f
      - run: cp ./main/LICENSE docs -f

      - working-directory: docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated docs"
          git push
