name: Test

on:
  push:
    branches: [main]
    paths:
      - packages/**
      - .github/workflows/test.yml

  pull_request:
    branches: [main]
    paths:
      - packages/**
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn ci
      - run: yarn lint
      - run: yarn bootstrap
      - run: yarn test:ci

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
